#!/bin/bash
# Add utils
export PYTHONPATH=$PYTHONPATH:`realpath ./utils`

# Download preprocessed dwi data
pushd . 
cd ./data
osf -p cmq8a fetch ds000221_subject/ds000221_sub-010006.zip 
unzip ds000221_sub-010006.zip
rm sub-010006.zip
popd 