name: dc-dmri

channels:
  - default
  - conda-forge

dependencies:
  - python=3.8.*
  - pip
  - git
  - dipy=1.3.0
  - fury=0.6.1
  - jupyter_contrib_nbextensions
  - matplotlib
  - nibabel
  - nilearn=0.7.0
  - numpy
  - osfclient
  - pandas
  - seaborn

  - pip:
      - pybids
